using System.Text.Json.Serialization;
namespace RPM.Application.DTOs.Vitals;

/// <summary>Payload coming from a watch or ingest endpoint.</summary>
public record VitalIngestionDto(
    Guid PatientId,
    Guid DeviceId,
    float? HeartRateBpm,
    float? SpO2Percent,
    float? SystolicBp,
    float? DiastolicBp,
    float? TemperatureC,
    int? Steps,
    float? Calories,
    bool FallDetected,
    bool IsWearing,
    float? SkinTemperatureC = null,
    /// <summary>Alias of <see cref="TemperatureC"/> (ambient room) for watch/mobile/web clients.</summary>
    [property: JsonPropertyName("ambientTemperatureC")] float? AmbientTemperatureC = null,
    [property: JsonPropertyName("hrvMs")] float? HeartRateVariabilityMs = null,
    float? RestingHeartRateBpm = null,
    float? MaxHeartRateBpm = null,
    float? RespirationRateBpm = null,
    float? DistanceMeters = null,
    int? FloorsClimbed = null,
    int? ActiveMinutes = null,
    float? StressScore = null,
    float? SleepScore = null,
    int? SleepDurationMinutes = null,
    float? BodyFatPercent = null,
    float? MuscleMassKg = null,
    float? BodyWaterPercent = null,
    float? BasalMetabolicRate = null,
    [property: JsonPropertyName("ecgAvgHeartRateBpm")] float? EcgAverageHeartRate = null,
    string? EcgClassification = null,
    string? EcgWaveformJson = null,
    float? BloodGlucoseMgDl = null,
    float? BatteryLevel = null);

/// <summary>Full vital reading returned to clients.</summary>
public record VitalRecordDto(
    Guid Id,
    Guid PatientId,
    Guid DeviceId,
    float? HeartRateBpm,
    float? SpO2Percent,
    float? SystolicBp,
    float? DiastolicBp,
    float? TemperatureC,
    int? StepsCount,
    float? CaloriesBurned,
    bool FallDetected,
    bool IsWearing,
    DateTime RecordedAt,
    float? SkinTemperatureC = null,
    /// <summary>Alias of <see cref="TemperatureC"/> (ambient room) for watch/mobile/web clients.</summary>
    [property: JsonPropertyName("ambientTemperatureC")] float? AmbientTemperatureC = null,
    [property: JsonPropertyName("hrvMs")] float? HeartRateVariabilityMs = null,
    float? RestingHeartRateBpm = null,
    float? MaxHeartRateBpm = null,
    float? RespirationRateBpm = null,
    float? DistanceMeters = null,
    int? FloorsClimbed = null,
    int? ActiveMinutes = null,
    float? StressScore = null,
    float? SleepScore = null,
    int? SleepDurationMinutes = null,
    float? BodyFatPercent = null,
    float? MuscleMassKg = null,
    float? BodyWaterPercent = null,
    float? BasalMetabolicRate = null,
    [property: JsonPropertyName("ecgAvgHeartRateBpm")] float? EcgAverageHeartRate = null,
    string? EcgClassification = null,
    string? EcgWaveformJson = null,
    float? BloodGlucoseMgDl = null,
    float? BatteryLevel = null);

public record VitalsPagedDto(IEnumerable<VitalRecordDto> Items, long TotalCount, int Page, int PageSize);

public record AlertThresholdDto(
    float MinHeartRate,
    float MaxHeartRate,
    float MinSpO2,
    float MaxSystolicBp,
    float MaxDiastolicBp,
    float MaxTemperatureC,
    float MaxSkinTemperatureC = 38.0f,
    float MinRespirationRate = 8,
    float MaxRespirationRate = 24,
    float MaxStressScore = 80,
    float MinBloodGlucoseMgDl = 70,
    float MaxBloodGlucoseMgDl = 180);
